owner: conscherry
repo: status

assignees:
  - xgarciadevs

secrets:
  - KINDBOT_API_URL
  - PROJECT_HOST_URL
  - NOTIFICATION_DISCORD_WEBHOOK_URL

sites:
  - name: API Services
    url: https://conscherry.com/api/health
    __dangerous__body_down_if_text_missing: '"status":"ok"'
  - name: Conscherry
    url: https://conscherry.com
  - name: Conscherry Dashboard
    url: https://dashboard.conscherry.com
  - name: Helpdesk
    url: https://helpdesk.conscherry.com/
  - name: Indenti Project
    url: https://indenti.net
  - name: KindBot Health
    url: $KINDBOT_API_URL
    icon: https://conscherry.com/projects/KindBot.webp
    __dangerous__body_down_if_text_missing: '"ok":true'
  - name: Labs API Services
    url: https://labs.conscherry.com/api/health
    icon: https://conscherry.com/projects/discordlabs.png
  - name: Labs Project
    url: https://labs.conscherry.com/
    icon: https://conscherry.com/projects/discordlabs.png
  - name: Project Host
    url: $PROJECT_HOST_URL
    icon: https://conscherry.com/branding/Conscherry_Logo.png
    __dangerous__body_down_if_text_missing: '"ok":true'
  - name: The Gobble Project
    url: https://playgobble.xyz

status-website:
  cname: status.conscherry.com
  logoHref: https://status.conscherry.com
  logoUrl: https://status.conscherry.com/logo.png
  favicon: https://status.conscherry.com/logo.png
  name: Conscherry
  introTitle: "Welcome to the Conscherry Status Page"
  introMessage: Here you can find the current status of our services and any ongoing incidents. If you have any questions or concerns, please reach out to us through our support channels.
  navbar:
    - title: Overview
      href: /
    - title: Help
      href: https://conscherry.com/help
    - title: Website
      href: https://conscherry.com
  theme: light
  themeUrl: https://raw.githubusercontent.com/conscherry/status/refs/heads/master/assets/theme.css
  links:
    - rel: stylesheet
      href: https://raw.githubusercontent.com/conscherry/status/refs/heads/master/assets/theme.css

i18n:
  footer: "[Conscherry](https://conscherry.com) • Maintained by Xavier Garcia • Powered by [Upptime](https://upptime.js.org) • [View source]($REPO)"
